/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8_danielsagastume;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agregar = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jd_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jd_apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jd_nacionalidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jd_residencia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jd_sexo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jd_cuenta = new javax.swing.JFormattedTextField();
        jd_profecion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jd_facultad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cb_persona = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jd_trabajo = new javax.swing.JTextField();
        trabajo = new javax.swing.ButtonGroup();
        jd_busqueda = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        b_cuenta = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        busqueda_result = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        cb_persona1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        b_filtro = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        parametro = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();

        jLabel2.setText("NOMBRE:");
        jd_agregar.getContentPane().add(jLabel2, java.awt.BorderLayout.CENTER);

        jd_nombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jd_agregar.getContentPane().add(jd_nombre, java.awt.BorderLayout.PAGE_START);

        jLabel3.setText("APELLIDO:");
        jd_agregar.getContentPane().add(jLabel3, java.awt.BorderLayout.PAGE_END);

        jd_apellido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jd_agregar.getContentPane().add(jd_apellido, java.awt.BorderLayout.LINE_END);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("APELLIDO:");
        jd_agregar.getContentPane().add(jLabel4, java.awt.BorderLayout.LINE_START);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jd_agregar.getContentPane().add(jSpinner1, java.awt.BorderLayout.CENTER);

        jLabel5.setText("NACIONALIDAD:");
        jd_agregar.getContentPane().add(jLabel5, java.awt.BorderLayout.CENTER);

        jd_nacionalidad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jd_agregar.getContentPane().add(jd_nacionalidad, java.awt.BorderLayout.CENTER);

        jLabel6.setText("LUGAR DE RESIDENCIA:");
        jd_agregar.getContentPane().add(jLabel6, java.awt.BorderLayout.CENTER);

        jd_residencia.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jd_agregar.getContentPane().add(jd_residencia, java.awt.BorderLayout.CENTER);

        jLabel7.setText("SEXO:");
        jd_agregar.getContentPane().add(jLabel7, java.awt.BorderLayout.CENTER);

        jd_sexo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jd_agregar.getContentPane().add(jd_sexo, java.awt.BorderLayout.CENTER);

        jLabel8.setText("NUMERO DE CUENTA:");
        jd_agregar.getContentPane().add(jLabel8, java.awt.BorderLayout.CENTER);

        jd_cuenta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jd_cuenta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jd_agregar.getContentPane().add(jd_cuenta, java.awt.BorderLayout.CENTER);

        jd_profecion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jd_agregar.getContentPane().add(jd_profecion, java.awt.BorderLayout.CENTER);

        jLabel9.setText("PROFESION:");
        jd_agregar.getContentPane().add(jLabel9, java.awt.BorderLayout.CENTER);

        jLabel10.setText("LUGAR DE TRABAJO:");
        jd_agregar.getContentPane().add(jLabel10, java.awt.BorderLayout.CENTER);

        trabajo.add(jRadioButton1);
        jRadioButton1.setText("NO");
        jd_agregar.getContentPane().add(jRadioButton1, java.awt.BorderLayout.CENTER);

        trabajo.add(jRadioButton2);
        jRadioButton2.setText("Si");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jd_agregar.getContentPane().add(jRadioButton2, java.awt.BorderLayout.CENTER);

        jLabel11.setText("TIPO DE PERSONA:");
        jd_agregar.getContentPane().add(jLabel11, java.awt.BorderLayout.CENTER);

        jd_facultad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jd_agregar.getContentPane().add(jd_facultad, java.awt.BorderLayout.CENTER);

        jLabel12.setText("FACULTAD:");
        jd_agregar.getContentPane().add(jLabel12, java.awt.BorderLayout.CENTER);

        cb_persona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Docente", "Administrativo", "Ejecutivo", "Decano" }));
        jd_agregar.getContentPane().add(cb_persona, java.awt.BorderLayout.CENTER);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("AGREGAR");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jd_agregar.getContentPane().add(jButton2, java.awt.BorderLayout.CENTER);
        jd_agregar.getContentPane().add(jd_trabajo, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel2.setName(""); // NOI18N

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("INGRESE EL NUMERO DE CUENTA:");

        b_cuenta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        busqueda_result.setEditable(false);
        busqueda_result.setColumns(20);
        busqueda_result.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        busqueda_result.setRows(5);
        jScrollPane1.setViewportView(busqueda_result);

        jButton4.setText("Search...");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(b_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addComponent(jLabel13)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(b_cuenta))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Busqueda llave", jPanel2);

        jLabel14.setText("SELECCIONE EL TIPO DE PERSONA");

        cb_persona1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cb_persona1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Docente", "Administrativo", "Ejecutivo", "Decano" }));

        jButton5.setText("FILTRAR");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        b_filtro.setColumns(20);
        b_filtro.setRows(5);
        jScrollPane2.setViewportView(b_filtro);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cb_persona1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_persona1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Busqueda por tipo", jPanel3);

        jLabel15.setText("PARAMETRO");

        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Apellido", "Edad", "Nacionalidad", "Residencia", "Sexo", "Cuenta", "Profesion", "Trabajo", "Facultad", "Tipo" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton6.setText("X");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(245, 245, 245))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(parametro, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parametro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Filtro por parametro", jPanel4);

        javax.swing.GroupLayout jd_busquedaLayout = new javax.swing.GroupLayout(jd_busqueda.getContentPane());
        jd_busqueda.getContentPane().setLayout(jd_busquedaLayout);
        jd_busquedaLayout.setHorizontalGroup(
            jd_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jd_busquedaLayout.setVerticalGroup(
            jd_busquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("CRUD PERSONAS");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 134, 262, 72));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LABORATORIO 9");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 37, 383, 71));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setForeground(new java.awt.Color(102, 0, 102));

        jButton3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton3.setText("BUSQUEDA");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // Seleccionar una opcion
        int op = Integer.parseInt(JOptionPane.showInputDialog("Ingrese que opcion desea\n"
                + "1. Agregar persona\n"
                + "2. Modificar persona\n"
                + "3. Eliminar persona"));
        switch (op) {
            case 1:
                jd_agregar.setModal(true);
                jd_agregar.pack();
                jd_agregar.setLocationRelativeTo(this);
                jd_agregar.setVisible(true);
                break;
            case 2:
                ArrayList<String> usuarios = new ArrayList();
                ArrayList<Integer> cuenta = new ArrayList();
                Dba db = new Dba("./bd_users.mdb");
                db.conectar();
                try {
                    db.query.execute("select Nombre,cuenta from alumnos");
                    ResultSet rs = db.query.getResultSet();
                    while (rs.next()) {
                        usuarios.add(rs.getString(1));
                        cuenta.add(rs.getInt(2));
                    }
                } catch (SQLException ex) {
                }
                db.desconectar();
                String salida = "";
                for (int i = 0; i < usuarios.size(); i++) {
                    salida += i + "- " + usuarios.get(i) + " Cuenta-" + cuenta.get(i) + "\n";
                }
                int select = Integer.parseInt(JOptionPane.showInputDialog("Seleccione el nombre del usuario:\n" + salida));
                int op2 = Integer.parseInt(JOptionPane.showInputDialog("ingrese la opcion que quiere modificar:\n"
                        + "1. Modificar nombre\n"
                        + "2. Modificar apellido\n"
                        + "3. Modificar Edad\n"
                        + "4. Modificar Nacionalidad\n"
                        + "5. Modificar lugar de residencia"
                        + "6. Modificar Sexo\n"
                        + "7. Modificar Numero de cuenta\n"
                        + "8. Modificar Profesion\n"
                        + "9. Modificar Lugar de trabajo\n"
                        + "10. Modifcar Facultad"
                        + "11. Modificar Tipo de persona"));
                if (op2 == 1) {
                    String nom = JOptionPane.showInputDialog("Ingrese el nuevo nombre: ");
                    db.conectar();
                    try {
                        db.query.execute("update alumnos"
                                + " set Nombre='" + nom + "'"
                                + " where Nombre='" + usuarios.get(select) + "'"
                                + " and Cuenta=" + cuenta.get(select));
                        db.commit();
                    } catch (SQLException ex) {
                    }
                    db.desconectar();
                    JOptionPane.showMessageDialog(this, "Usuario modificado");
                } else if (op2 == 2) {
                    String nom = JOptionPane.showInputDialog("Ingrese el nuevo apellido: ");
                    db.conectar();
                    try {
                        db.query.execute("update alumnos"
                                + " set Apellido='" + nom + "'"
                                + " where Nombre='" + usuarios.get(select) + "'"
                                + " and Cuenta=" + cuenta.get(select));
                        db.commit();
                    } catch (SQLException ex) {
                    }
                    db.desconectar();
                    JOptionPane.showMessageDialog(this, "Usuario modificado");
                } else if (op2 == 3) {
                    String nom = JOptionPane.showInputDialog("Ingrese la nueva edad: ");
                    int cuenta_ = Integer.parseInt(nom);
                    db.conectar();
                    try {
                        db.query.execute("update alumnos"
                                + " set Edad=" + cuenta_
                                + " where Nombre='" + usuarios.get(select) + "'"
                                + " and Cuenta=" + cuenta.get(select));
                        db.commit();
                    } catch (SQLException ex) {
                    }
                    db.desconectar();
                    JOptionPane.showMessageDialog(this, "Usuario modificado");
                } else if (op2 == 4) {
                    String nom = JOptionPane.showInputDialog("Ingrese la nueva nacionalidad: ");
                    db.conectar();
                    try {
                        db.query.execute("update alumnos"
                                + " set Nacionalidad='" + nom + "'"
                                + " where Nombre='" + usuarios.get(select) + "'"
                                + " and Cuenta=" + cuenta.get(select));
                        db.commit();
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                    db.desconectar();
                    JOptionPane.showMessageDialog(this, "Usuario modificado");
                } else if (op2 == 5) {
                    String nom = JOptionPane.showInputDialog("Ingrese el lugar de residencia: ");
                    db.conectar();
                    try {
                        db.query.execute("update alumnos"
                                + " set Residencia='" + nom + "'"
                                + " where Nombre='" + usuarios.get(select) + "'"
                                + " and Cuenta=" + cuenta.get(select));
                        db.commit();
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                    db.desconectar();
                    JOptionPane.showMessageDialog(this, "Usuario modificado");
                } else if (op2 == 6) {
                    String nom = JOptionPane.showInputDialog("Ingrese el nuevo sexo: ");
                    db.conectar();
                    try {
                        db.query.execute("update alumnos"
                                + " set Sexo='" + nom + "'"
                                + " where Nombre='" + usuarios.get(select) + "'"
                                + " and Cuenta=" + cuenta.get(select));
                        db.commit();
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                    db.desconectar();
                    JOptionPane.showMessageDialog(this, "Usuario modificado");
                } else if (op2 == 7) {
                    String nom = JOptionPane.showInputDialog("Ingrese el nuevo numero de cuenta: ");
                    int cuenta_ = Integer.parseInt(nom);
                    db.conectar();
                    try {
                        db.query.execute("update alumnos"
                                + " set Cuenta=" + cuenta_
                                + " where Nombre='" + usuarios.get(select) + "'"
                                + " and Cuenta=" + cuenta.get(select));
                        db.commit();
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                    db.desconectar();
                    JOptionPane.showMessageDialog(this, "Usuario modificado");
                } else if (op2 == 8) {
                    String nom = JOptionPane.showInputDialog("Ingrese la nueva profesion: ");
                    db.conectar();
                    try {
                        db.query.execute("update alumnos"
                                + " set Profesion='" + nom + "'"
                                + " where Nombre='" + usuarios.get(select) + "'"
                                + " and Cuenta=" + cuenta.get(select));
                        db.commit();
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                    db.desconectar();
                    JOptionPane.showMessageDialog(this, "Usuario modificado");
                } else if (op2 == 9) {
                    String nom = JOptionPane.showInputDialog("Ingrese el nuevo lugar de trabajo: ");
                    db.conectar();
                    try {
                        db.query.execute("update alumnos"
                                + " set Trabajo='" + nom + "'"
                                + " where Nombre='" + usuarios.get(select) + "'"
                                + " and Cuenta=" + cuenta.get(select));
                        db.commit();
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                    db.desconectar();
                    JOptionPane.showMessageDialog(this, "Usuario modificado");
                } else if (op2 == 10) {
                    String nom = JOptionPane.showInputDialog("Ingrese la facultad: ");
                    db.conectar();
                    try {
                        db.query.execute("update alumnos"
                                + " set Facultad='" + nom + "'"
                                + " where Nombre='" + usuarios.get(select) + "'"
                                + " and Cuenta=" + cuenta.get(select));
                        db.commit();
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                    db.desconectar();
                    JOptionPane.showMessageDialog(this, "Usuario modificado");
                } else if (op == 11) {
                    String nom = JOptionPane.showInputDialog("Ingrese el nuevo tipo de persona: ");
                    db.conectar();
                    try {
                        db.query.execute("update alumnos"
                                + " set Tipo de persona='" + nom + "'"
                                + " where Nombre='" + usuarios.get(select) + "'"
                                + " and Cuenta=" + cuenta.get(select));
                        db.commit();
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                    db.desconectar();
                    JOptionPane.showMessageDialog(this, "Usuario modificado");
                }
                break;
            case 3:
                ArrayList<String> usuarios1 = new ArrayList();
                ArrayList<Integer> cuenta1 = new ArrayList();
                Dba db1 = new Dba("./bd_users.mdb");
                db1.conectar();
                try {
                    db1.query.execute("select Nombre,cuenta from alumnos");
                    ResultSet rs = db1.query.getResultSet();
                    while (rs.next()) {
                        usuarios1.add(rs.getString(1));
                        cuenta1.add(rs.getInt(2));
                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
                db1.desconectar();
                String salida1 = "";
                for (int i = 0; i < usuarios1.size(); i++) {
                    salida1 += i + "- " + usuarios1.get(i) + " Cuenta-" + cuenta1.get(i) + "\n";
                }
                int select1 = Integer.parseInt(JOptionPane.showInputDialog("Seleccione el nombre del usuario:\n" + salida1));
                db1.conectar();
                try {
                    db1.query.execute("delete from alumnos "
                            + "where Nombre='" + usuarios1.get(select1) + "'"
                            + " and Cuenta=" + cuenta1.get(select1));
                    db1.commit();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
                db1.desconectar();
                JOptionPane.showMessageDialog(this, "Usuario eliminado");
                break;
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        //Si tiene lugar de trabajo
        jd_trabajo.setEnabled(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // Agregar persona
        Dba db = new Dba("./bd_users.mdb");
        int edad = (Integer) jSpinner1.getValue();
        String tipo = cb_persona.getItemAt(cb_persona.getSelectedIndex());
        if (jRadioButton1.isSelected()) {
            jd_trabajo.setText("No");
        }
        db.conectar();
        try {
            db.query.execute("INSERT INTO alumnos"
                    + " VALUES ('" + jd_nombre.getText() + "', '" + jd_apellido.getText() + "', "
                    + edad + ", '" + jd_nacionalidad.getText() + "','" + jd_residencia.getText() + "','"
                    + jd_sexo.getText() + "'," + Integer.parseInt(jd_cuenta.getText()) + ",'" + jd_profecion.getText() + "','" + jd_trabajo.getText() + "','" + jd_facultad.getText() + "','" + tipo + "')");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.commit();
        db.desconectar();
        JOptionPane.showMessageDialog(this, "usuario agregado");
        jd_nombre.setText("");
        jd_apellido.setText("");
        jd_nacionalidad.setText("");
        jd_residencia.setText("");
        jd_sexo.setText("");
        jd_profecion.setText("");
        jd_trabajo.setText("");
        jd_facultad.setText("");
        jd_cuenta.setText("");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        jd_busqueda.setModal(true);
        jd_busqueda.pack();
        jd_busqueda.setLocationRelativeTo(this);
        jd_busqueda.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        Dba db = new Dba("./bd_users.mdb");
        String salida = "";
        db.conectar();
        try {
            db.query.execute("select * from alumnos where Cuenta=" + b_cuenta.getText());
            ResultSet rs = db.query.getResultSet();
            while (rs.next()) {
                salida += "======================================\n"
                        + "Nombre= " + rs.getString(1) + "\n"
                        + "Apellido= " + rs.getString(2) + "\n"
                        + "Edad= " + rs.getInt(3) + "\n"
                        + "Nacionalidad= " + rs.getString(4) + "\n"
                        + "Lugar de residencia= " + rs.getString(5) + "\n"
                        + "Sexo de nacimiento= " + rs.getString(6) + "\n"
                        + "Numero de cuenta= " + rs.getInt(7) + "\n"
                        + "Profesion= " + rs.getString(8) + "\n"
                        + "Lugar de trabajo= " + rs.getString(9) + "\n"
                        + "Facultad= " + rs.getString(10) + "\n"
                        + "Tipo de persona= " + rs.getString(11) + "\n"
                        + "======================================";
            }
        } catch (SQLException ex) {
        }
        db.desconectar();
        busqueda_result.setText(salida);

    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        Dba db = new Dba("./bd_users.mdb");
        String salida1 = "";
        db.conectar();
        String tipo = cb_persona1.getItemAt(cb_persona1.getSelectedIndex());
        try {
            db.query.execute("select * from alumnos where Tipo='" + tipo + "'");
            ResultSet rs = db.query.getResultSet();
            while (rs.next()) {
                salida1 += "======================================\n"
                        + "Nombre= " + rs.getString(1) + "\n"
                        + "Apellido= " + rs.getString(2) + "\n"
                        + "Edad= " + rs.getInt(3) + "\n"
                        + "Nacionalidad= " + rs.getString(4) + "\n"
                        + "Lugar de residencia= " + rs.getString(5) + "\n"
                        + "Sexo de nacimiento= " + rs.getString(6) + "\n"
                        + "Numero de cuenta= " + rs.getInt(7) + "\n"
                        + "Profesion= " + rs.getString(8) + "\n"
                        + "Lugar de trabajo= " + rs.getString(9) + "\n"
                        + "Facultad= " + rs.getString(10) + "\n"
                        + "Tipo de persona= " + rs.getString(11) + "\n"
                        + "======================================";
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
        if (salida1.equals("")) {
            salida1 = "Usuarios no encontrados";
            b_filtro.setText(salida1);
        } else {
            b_filtro.setText(salida1);
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        busqueda_result.setText("");
        b_filtro.setText("");
        jTextArea1.setText("");
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        if (jComboBox1.getItemAt(jComboBox1.getSelectedIndex()).equals("Edad")) {
            int edad = Integer.parseInt(parametro.getText());
            Dba db = new Dba("./bd_users.mdb");
            String salida1 = "";
            db.conectar();
            try {
                db.query.execute("select * from alumnos where Edad='" + edad + "'");
                ResultSet rs = db.query.getResultSet();
                while (rs.next()) {
                    salida1 += "======================================\n"
                            + "Nombre= " + rs.getString(1) + "\n"
                            + "Apellido= " + rs.getString(2) + "\n"
                            + "Edad= " + rs.getInt(3) + "\n"
                            + "Nacionalidad= " + rs.getString(4) + "\n"
                            + "Lugar de residencia= " + rs.getString(5) + "\n"
                            + "Sexo de nacimiento= " + rs.getString(6) + "\n"
                            + "Numero de cuenta= " + rs.getInt(7) + "\n"
                            + "Profesion= " + rs.getString(8) + "\n"
                            + "Lugar de trabajo= " + rs.getString(9) + "\n"
                            + "Facultad= " + rs.getString(10) + "\n"
                            + "Tipo de persona= " + rs.getString(11) + "\n"
                            + "======================================";
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            db.desconectar();
            if (salida1.equals("")) {
                salida1 = "Usuarios no encontrados";
                jTextArea1.setText(salida1);
            } else {
                jTextArea1.setText(salida1);
            }
            parametro.setText("");
        } else if (jComboBox1.getItemAt(jComboBox1.getSelectedIndex()).equals("Cuenta")) {
            int cuenta = Integer.parseInt(parametro.getText());
            Dba db = new Dba("./bd_users.mdb");
            String salida1 = "";
            db.conectar();
            try {
                db.query.execute("select * from alumnos where Cuenta='" + cuenta + "'");
                ResultSet rs = db.query.getResultSet();
                while (rs.next()) {
                    salida1 += "======================================\n"
                            + "Nombre= " + rs.getString(1) + "\n"
                            + "Apellido= " + rs.getString(2) + "\n"
                            + "Edad= " + rs.getInt(3) + "\n"
                            + "Nacionalidad= " + rs.getString(4) + "\n"
                            + "Lugar de residencia= " + rs.getString(5) + "\n"
                            + "Sexo de nacimiento= " + rs.getString(6) + "\n"
                            + "Numero de cuenta= " + rs.getInt(7) + "\n"
                            + "Profesion= " + rs.getString(8) + "\n"
                            + "Lugar de trabajo= " + rs.getString(9) + "\n"
                            + "Facultad= " + rs.getString(10) + "\n"
                            + "Tipo de persona= " + rs.getString(11) + "\n"
                            + "======================================";
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            db.desconectar();
            if (salida1.equals("")) {
                salida1 = "Usuarios no encontrados";
                jTextArea1.setText(salida1);
            } else {
                jTextArea1.setText(salida1);
            }
            parametro.setText("");
        } else {
            Dba db = new Dba("./bd_users.mdb");
            String salida1 = "";
            db.conectar();
            String tipo = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
            try {
                db.query.execute("select * from alumnos "
                        + "where " + tipo + "='" + parametro.getText() + "'");
                ResultSet rs = db.query.getResultSet();
                while (rs.next()) {
                    salida1 += "======================================\n"
                            + "Nombre= " + rs.getString(1) + "\n"
                            + "Apellido= " + rs.getString(2) + "\n"
                            + "Edad= " + rs.getInt(3) + "\n"
                            + "Nacionalidad= " + rs.getString(4) + "\n"
                            + "Lugar de residencia= " + rs.getString(5) + "\n"
                            + "Sexo de nacimiento= " + rs.getString(6) + "\n"
                            + "Numero de cuenta= " + rs.getInt(7) + "\n"
                            + "Profesion= " + rs.getString(8) + "\n"
                            + "Lugar de trabajo= " + rs.getString(9) + "\n"
                            + "Facultad= " + rs.getString(10) + "\n"
                            + "Tipo de persona= " + rs.getString(11) + "\n"
                            + "======================================";
                }
            } catch (SQLException ex) {
            }
            db.desconectar();
            if (salida1.equals("")) {
                salida1 = "Usuarios no encontrados";
                jTextArea1.setText(salida1);
            } else {
                jTextArea1.setText(salida1);
            }
            parametro.setText("");
        }
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField b_cuenta;
    private javax.swing.JTextArea b_filtro;
    private javax.swing.JTextArea busqueda_result;
    private javax.swing.JComboBox<String> cb_persona;
    private javax.swing.JComboBox<String> cb_persona1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JDialog jd_agregar;
    private javax.swing.JTextField jd_apellido;
    private javax.swing.JDialog jd_busqueda;
    private javax.swing.JFormattedTextField jd_cuenta;
    private javax.swing.JTextField jd_facultad;
    private javax.swing.JTextField jd_nacionalidad;
    private javax.swing.JTextField jd_nombre;
    private javax.swing.JTextField jd_profecion;
    private javax.swing.JTextField jd_residencia;
    private javax.swing.JTextField jd_sexo;
    private javax.swing.JTextField jd_trabajo;
    private javax.swing.JTextField parametro;
    private javax.swing.ButtonGroup trabajo;
    // End of variables declaration//GEN-END:variables
}
